spring:
  application:
    name: skillMgrApi
  datasource:
    url: jdbc:mysql://mysql:3306/skillMgr
    username: skillMgr
    password: password
    driverClassName: com.mysql.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      pool-name: ConnectionPool
      leakDetectionThreshold: 5000
      connection-test-query: SELECT 1
      minimum-idle: 5
      maximum-pool-size: 10
      auto-commit: false
  jpa:
    database: MYSQL
    hibernate:
      ddl-auto: update
  cloud:
    service-registry:
      auto-registration:
        enabled: true
server:
  port: 8081
eureka:
  client:
    enabled: true
    serviceUrl:
      defaultZone: http://discovery:8761/eureka
logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    jp.co.sunarch: DEBUG
  file: logs/${spring.application.name}.log
