spring:
  application:
    name: skillMgrApi
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:skillMgr;DB_CLOSE_ON_EXIT=TRUE;MODE=MySQL
    username: sa
    password: 
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      pool-name: ConnectionPool
      leakDetectionThreshold: 5000
      connection-test-query: SELECT 1
      minimum-idle: 5
      maximum-pool-size: 10
      auto-commit: false
    initialization-mode: embedded
  jpa:
    database: MYSQL
    hibernate:
      ddl-auto: update
  cloud:
    service-registry:
      auto-registration:
        enabled: false
  h2:
    console:
      enabled: true
server:
  port: 8081
eureka:
  client:
    enabled: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    jp.co.sunarch: DEBUG
  file: logs/${spring.application.name}.log
