spring:
  application:
    name: skillMgrApi
  datasource:
    url: jdbc:mysql://mysql:3306/skillMgr
    username: skillMgr
    password: password
    driverClassName: com.mysql.jdbc.Driver
  jpa:
    database: MYSQL
    hibernate:
      ddl-auto: update
server:
  port: 8081
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost
logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    jp.co.sunarch: DEBUG
  file: logs/${spring.application.name}.log
